### ISSUE TITLE
year_align set incorrectly in IAF stream.xml files

### ISSUE THREAD

**Issue by dougiesquire** [COSIMA/MOM6-CICE6#20]
The `year_align` parameter is set to 1 in the `*.stream.xml` files. This is suitable for the RYF configurations, but not for IAF. For IAF, `year_align` should be equal to `year_first` so that the simulation and forcing years are aligned. See [here](https://escomp.github.io/CDEPS/versions/master/html/streams.html#definitions-of-each-keys-used-in-stream-definition-file) for details.

**Comment by dougiesquire** [comment]
Closed by #21

**Comment by aekiss** [comment]
FYI just adding a relevant issue from OM2: https://github.com/COSIMA/access-om2/issues/149

When running multiple cycles, each cycle needs to begin from the same initial year (ie the multiple cycles form an ensemble, not a consecutive sequence) to avoid leap year problems, especially now we're using a 61-year IAF cycle.
