### ISSUE TITLE
Create OM3-Tools and move generate xml scripts there

### ISSUE THREAD

**Issue by anton-seaice** [COSIMA/MOM6-CICE6#29]
To-do

- Create a COSIMA/OM3-Tools repo for informal tools / items non essential to running OM3 but are useful records to have.
- Move the generate xml scripts there

I suggest we don't review items going into the OM3 tools repo on the basis that the resulting configurations are reviewed (like this repo).

@micaeljtoliveira - Do you want to start a repo?

**Comment by micaeljtoliveira** [comment]
I already have a repo started, currently living in my private github account. Currently it includes code to read and write several of the configuration files from and to a python dict.

I'm planning on adding a few more things related to extracting information from the output, in particular the profiling info.

Happy to add any Python code related to OM3, but I don't want this repo to simply by a place to store random scripts. The code must be properly tested and documented, and so code review is essential IMHO.

**Comment by anton-seaice** [comment]
> Happy to add any Python code related to OM3, but I don't want this repo to simply by a place to store random scripts. The code must be properly tested and documented, and so code review is essential IMHO.

I don't mind - but we end up in the situation where both the config and the scripts used to create them are reviewed, which is a bit redundant, especially when the configs are human readable / editable like they are in this case.

**Comment by micaeljtoliveira** [comment]
The problem is that, once you make some code available online, anyone can use it, and there's no guarantee the resulting configuration will  be reviewed by anyone.

In any case, not saying we can't have such repo where things are not reviewed, but in that case I would prefer it to be separate from the one I already started.

**Comment by dougiesquire** [comment]
I assume this is the repo your talking about @micaeljtoliveira: https://github.com/micaeljtoliveira/om3utils.

So far, the "OM3-peripheral" tools we have that need a home are:
- [`generate_mesh.py`](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_mesh.py) - for generating input mesh files
- [`generate_xml_datm.py`](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_xml_datm.py) and [`generate_xml_drof.py`](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_xml_drof.py) - for generating xml data stream files
- [`WW3_PreProc`](https://github.com/COSIMA/MOM6-CICE6-WW3/tree/1deg_jra55do_ryf/WW3_PreProc) - for generating WW3 configurations

Anything else?

The main question for me is whether we want to include all this functionality in a single Python package like om3utils? That's nice from a user perspective, provided the package is well-designed, maintained, tested and documented, which requires effort and forethought. The other option is just to have a repo that grows organically, with people adding their code/scripts to subfolders along with some documentation. Either way, I think the code should be reviewed.

**Comment by anton-seaice** [comment]
> So far, the "OM3-peripheral" tools we have that need a home are:
> 
>     * [`generate_mesh.py`](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_mesh.py) - for generating input mesh files
> 
>     * [`generate_xml_datm.py`](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_xml_datm.py) and [`generate_xml_drof.py`](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_xml_drof.py) - for generating xml data stream files
> 
>     * [`WW3_PreProc`](https://github.com/COSIMA/MOM6-CICE6-WW3/tree/1deg_jra55do_ryf/WW3_PreProc) - for generating WW3 configurations
> 

I had assumed that the WW3 PreProc are more likely to be needed by someone running the model, and are unique to wavewatch? When the python scripts are likely to be only set up once for each resolution / input files and not changed by someone running the model.

Yeah - lets put on the agenda. This is starting to feel like a config generation package, which if we are serious about, we should also consider using it to generate/store configs for the different resolutions / forcings.

**Comment by micaeljtoliveira** [comment]
> I assume this is the repo your talking about @micaeljtoliveira: https://github.com/micaeljtoliveira/om3utils.

Yes.

> The main question for me is whether we want to include all this functionality in a single Python package like om3utils? That's nice from a user perspective, provided the package is well-designed, maintained, tested and documented, which requires effort and forethought. The other option is just to have a repo that grows organically, with people adding their code/scripts to subfolders along with some documentation. Either way, I think the code should be reviewed.

I was trying to go with the "well-designed, maintained, tested and documented" option for my repo, but that does not mean that one cannot have another repo for "quick and dirty" scripts that we might want to keep around for reproducibility.

**Comment by micaeljtoliveira** [comment]
Done here: https://github.com/COSIMA/om3-scripts/pull/4
