### ISSUE TITLE
Processor layout for 0.25deg configuration

### ISSUE THREAD

**Issue by dougiesquire** [COSIMA/MOM6-CICE6#38]
We haven't yet made any consideration of processor layout. Currently, each model component runs sequentially and is allocated a single 48-core node. We need to think about processor layout across the different components, and within each component (e.g. `LAYOUT` and `IO_LAYOUT` in MOM).

**Comment by aekiss** [comment]
Related: https://github.com/COSIMA/access-om3/issues/125

**Comment by aekiss** [comment]
Docs on CICE6 block distribution: https://cice-consortium-cice.readthedocs.io/en/cice6.5.0/user_guide/ug_implementation.html#performance

**Comment by micaeljtoliveira** [comment]
Latest MOM6 version has a new option to automatically perform land block elimination at _runtime_. This means one does not need to pre-generate a mask table for a given processor count. See [here](https://github.com/NCAR/MOM6/pull/263) for more details.

**Comment by anton-seaice** [comment]
This issue is superseded by https://github.com/COSIMA/access-om3/issues/148
