### ISSUE TITLE
MOM6 1deg configuration - No output generated for GMOM_JRA.mom6.h.rho2_*.nc

### ISSUE THREAD

**Issue by minghangli-uni** [COSIMA/MOM6-CICE6#40]
In the current MOM6 1deg configuration, there is no output generated for `GMOM_JRA.mom6.h.rho2_*.nc`.

A potential issue might be a typo identified in [diag_table](https://github.com/COSIMA/MOM6-CICE6/blob/fa4a80c786536c8b8beaf76538a9f778bab2f9ff/diag_table#L13), where `ocean_model_rho2` should be interchanged with `ocean_model`. But if that's indeed the case, all diagnostics present in `GMOM_JRA.mom6.h.rho2_*.nc` should be accessible in `GMOM_JRA.mom6.h.native_*.nc`.

Alternatively, if `GMOM_JRA.mom6.h.rho2_*.nc` comprises non-native vertical grid diagnostics, a parameter named `DIAG_COORD_DEF_Z` needs to be configured accordingly [here](https://ncar.github.io/MOM6/APIs/Diagnostics.html#remapped_diagnostics). Additionally, in the MOM6 regridding module, a coordinate name should be picked in one of these available [here](https://github.com/NCAR/MOM6/blob/2e77200bff72042bc05e5e5a957274df55493550/src/ALE/MOM_regridding.F90#L150C1-L160C76),
```
!> Documentation for coordinate options
character(len=*), parameter, public :: regriddingCoordinateModeDoc = &
                 " LAYER - Isopycnal or stacked shallow water layers\n"//&
                 " ZSTAR, Z* - stretched geopotential z*\n"//&
                 " SIGMA_SHELF_ZSTAR - stretched geopotential z* ignoring shelf\n"//&
                 " SIGMA - terrain following coordinates\n"//&
                 " RHO   - continuous isopycnal\n"//&
                 " HYCOM1 - HyCOM-like hybrid coordinate\n"//&
                 " HYBGEN - Hybrid coordinate from the Hycom hybgen code\n"//&
                 " SLIGHT - stretched coordinates above continuous isopycnal\n"//&
                 " ADAPTIVE - optimize for smooth neutral density surfaces"

```

**Comment by anton-seaice** [comment]
I am moderately confident we expect rho/density remapped fields as an output?

**Comment by aekiss** [comment]
The [pan-Antarctic diag_table](https://github.com/COSIMA/mom6-panan/blob/master/diag_table) uses `ocean_model_rho2`.

The set of diagnostics for these default configurations is yet to be decided, and will need some discussion with end-users, but will probably be some sort of mash-up of the pan-Antarctic MOM6 configuration https://github.com/COSIMA/mom6-panan/blob/master/diag_table and OM2 https://github.com/COSIMA/01deg_jra55_iaf/blob/master/ocean/diag_table

If the community prefers one file per variable as was done with the 0.1° IAF in OM2, `diag_table` would need to be generated by https://github.com/COSIMA/make_diag_table (which may need updating for MOM6).

**Comment by anton-seaice** [comment]
I guess we can update `MOM_input` then to turn on the rho2 output? Have you tried that @minghangli-uni?

**Comment by minghangli-uni** [comment]
@anton-seaice , I've managed to do that. 

By including `/g/data/ik11/inputs/mom6/panan-01/diag_rho2.nc` in our list of input files and adding the following snippet to `MOM_input`, we can produce rho2 outputs. My only concern is how `diag_rho2.nc` was generated.

```
NUM_DIAG_COORDS = 2
DIAG_COORDS = "z 01 ZSTAR", "rho2 02 RHO"
DIAG_COORD_DEF_01 = "FILE:ocean_vgrid.nc,interfaces=zeta"
DIAG_COORD_DEF_02 = "FILE:diag_rho2.nc,interfaces=rho2"
```

```
$ ncdump -h access-om3.mom6.h.rho2_1900_01.nc
netcdf access-om3.mom6.h.rho2_1900_01 {
dimensions:
	xh = 360 ;
	yh = 300 ;
	\02_l = 79 ;
	\02_i = 80 ;
	time = UNLIMITED ; // (1 currently)
	nv = 2 ;
	yq = 300 ;
	xq = 360 ;
variables:
	double xh(xh) ;
		xh:units = "degrees_east" ;
		xh:long_name = "h point nominal longitude" ;
...
```

**Comment by adele-morrison** [comment]
I think @AndyHoggANU made it?

**Comment by AndyHoggANU** [comment]
Aah, I think that might be right. Sorry for the lack of provenance there!
I think it came from here:
https://github.com/COSIMA/mom6-diagnostics/blob/main/PanAntarctic/inputs/RFNC1.ipynb
But it may not be quite what we want for the 1 degree, so might be worth talking about how we adjust it.
